### PR TITLE
enable building on non-x86 systems

### PR DESCRIPTION
**Pull request by mr-c**
Hello again. This is another patch from the Debian package of plink2. It enables building on non-x86 architectures link arm64, ppc64el, s390x, and more: https://buildd.debian.org/status/package.php?p=plink2

This also allows us to compile plink on x86 systems without advanced SIMD usage, as that is required by the Debian x86 64 and 32 bit architecture baselines. On x86 we make several plink2 binaries using the `SFX` shown below. At runtime a dispatcher script selects the most capable binary for the user's CPU.

You can see our compile recipe at https://salsa.debian.org/med-team/plink2/-/blob/master/debian/rules#L36 and the dispatcher script at https://salsa.debian.org/med-team/plink2/-/blob/master/debian/bin/simd-dispatch

If a CPU dispatcher was integrated into plink2 then this external script would not be necessary.

Please let me know what I can do to improve this PR so it gets merged. Thanks!

### CODE REVIEW

**Comment by chrchang** [comment]
Have you tested this on e.g. an ARM machine?  I wouldn't expect this to work at all, because the codebase currently includes some hardcoded unaligned copy operations.  I was planning to clean that up in a year or two (ideally after I could obtain an ARM MacBook to test with).

**Comment by mr-c** [comment]
@chrchang It built on arm64 https://buildd.debian.org/status/package.php?p=plink2&suite=sid and a basic test passed: https://ci.debian.net/packages/p/plink2/

**Comment by mr-c** [comment]
Here's the test script https://salsa.debian.org/med-team/plink2/-/blob/master/debian/tests/run-sample-analysis

**Comment by chrchang** [comment]
Ok, it's possible that I misunderstood the nature of arm64's behavior w.r.t. unaligned copies.  I will try to perform a more thorough test on EC2 within the next few days.

**Comment by mr-c** [comment]
Thanks. If there is a better post-installation test for Debian to run, please let us know

**Comment by mr-c** [comment]
Hello @chrchang ; is there anything I can do to get his PR merged? Thanks!

**Comment by chrchang** [comment]
Sorry about the delay; I am testing this on an EC2 A1 instance now and will merge it today if no problems arise.

**Comment by chrchang** [comment]
I'm currently resolving some system-specific build problems (e.g. "symbol lookup error: ./plink2: undefined symbol: ZSTD_compressStream2").  Will continue working on this over the long weekend.

**Comment by chrchang** [comment]
Ok, confirmed that this basically works, after making the same change to plink 1.9 and running the usual test suite.  I'll make a few tweaks in a subsequent revision so that it's easier for me to build this on a new EC2 A1 instance with Ubuntu 18.04, but merging this as-is first.

**Pull request merged**
